version: '3.2'

services:

  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile.cn
    entrypoint: ['/usr/src/fred/entrypoint.sh']
    volumes:
      - './services/backend:/usr/src/fred'
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=app.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/app_dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@db:5432/app_test
      - SECRET_KEY=change_this_to_some_random_key
    depends_on:
      - db

  db:
    build:
      context: ./services/db
      dockerfile: Dockerfile
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile.cn
    volumes:
      - './services/frontend:/usr/src/fred'
      - '/usr/src/fred/node_modules'
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_BACKEND_SERVICE_URL=http://localhost:5001
    depends_on:
      - backend
