version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    REACT_APP_BACKEND_SERVICE_URL: "http://fred-alb-869519198.us-east-1.elb.amazonaws.com"

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo logging in to ecr...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - echo building and testing dev images...
      - docker-compose up -d --build
      - docker-compose exec -T backend python -m pytest "app/tests" -p no:warnings --cov="app"
      - docker-compose exec -T frontend npm run test-ci

      - echo building images...
      - >
        docker build \
          -f services/backend/Dockerfile.prod \
          -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/fred-backend:prod \
          ./services/backend
      - >
        docker build \
          -f services/frontend/Dockerfile.prod \
          -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/fred-frontend:prod \
          --build-arg NODE_ENV=production \
          --build-arg REACT_APP_BACKEND_SERVICE_URL=$REACT_APP_BACKEND_SERVICE_URL \
          ./services/frontend
  post_build:
    commands:
    - echo pushing prod images to ecr...
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/fred-backend:prod
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/fred-frontend:prod
    # deploy in post_build will not success
    # deploy.sh need to be updated
    # - chmod +x deploy/aws/regular/deploy.sh
    # - bash deploy/aws/regular/deploy.sh
